#!/usr/bin/env bash
# tmux-powerkit theme — generated by aibox CLI from the active theme palette.
# Loaded via @powerkit_theme "custom" + @powerkit_custom_theme_path.
# Do NOT edit; re-run `aibox theme` to regenerate.

declare -gA THEME_COLORS=(
    # Core
    [background]="#FBF1C7"

    # Status bar
    [statusbar-bg]="#E6DDB7"
    [statusbar-fg]="#3C3836"

    # Session (status-left)
    [session-bg]="#AF3A03"
    [session-fg]="#FFFFFF"
    [session-prefix-bg]="#9D0006"
    [session-copy-bg]="#417956"
    [session-search-bg]="#946110"
    [session-command-bg]="#8F3F71"

    # Windows
    [window-active-base]="#AF3A03"
    [window-active-style]="bold"
    [window-inactive-base]="#786B5F"
    [window-inactive-style]="dim"
    [window-activity-style]="dim"
    [window-bell-style]="bold"
    [window-zoomed-bg]="#417956"

    # Panes
    [pane-border-active]="#AF3A03"
    [pane-border-inactive]="#786B5F"

    # Health / state segments (chevron color rotation source)
    [ok-base]="#8B593E"
    [good-base]="#746F0D"
    [info-base]="#417956"
    [warning-base]="#946110"
    [error-base]="#9D0006"
    [disabled-base]="#786B5F"

    # Messages
    [message-bg]="#E6DDB7"
    [message-fg]="#3C3836"

    # Popup & menu
    [popup-bg]="#E6DDB7"
    [popup-fg]="#3C3836"
    [popup-border]="#AF3A03"
    [menu-bg]="#E6DDB7"
    [menu-fg]="#3C3836"
    [menu-selected-bg]="#AF3A03"
    [menu-selected-fg]="#FFFFFF"
    [menu-border]="#AF3A03"
)

# Extra slots some plugins read directly — also derived from the palette so
# every chevron lands on a known-good bg.
declare -gA THEME_EXTRA=(
    [orange]="#AF3A03"
    [magenta]="#8F3F71"
    [surface]="#E6DDB7"
)
