" aibox.vim — generated by aibox CLI from the active theme palette.
" Do NOT edit; re-run `aibox theme` to regenerate.

hi clear
if exists("syntax_on")
  syntax reset
endif
let g:colors_name = "aibox"
set background=light

" ── UI chrome ──────────────────────────────────────────────────────────────
hi Normal         guifg=#3C3836     guibg=#FBF1C7     ctermfg=NONE ctermbg=NONE
hi NormalNC       guifg=#3C3836     guibg=#FBF1C7
hi LineNr         guifg=#928374  guibg=#FBF1C7
hi CursorLineNr   guifg=#D65D0E guibg=#EBDBB2 gui=bold
hi CursorLine     guibg=#EBDBB2
hi CursorColumn   guibg=#EBDBB2
hi ColorColumn    guibg=#EBDBB2
hi VertSplit      guifg=#928374  guibg=#FBF1C7
hi WinSeparator   guifg=#928374  guibg=#FBF1C7
hi StatusLine     guifg=#FBF1C7     guibg=#D65D0E gui=bold
hi StatusLineNC   guifg=#928374  guibg=#EBDBB2
hi TabLine        guifg=#928374  guibg=#EBDBB2
hi TabLineFill    guibg=#FBF1C7
hi TabLineSel     guifg=#FBF1C7     guibg=#D65D0E gui=bold
hi SignColumn     guifg=#928374  guibg=#FBF1C7
hi FoldColumn     guifg=#928374  guibg=#FBF1C7
hi Folded         guifg=#928374  guibg=#EBDBB2
hi NonText        guifg=#928374
hi EndOfBuffer    guifg=#FBF1C7     guibg=#FBF1C7
hi SpecialKey     guifg=#928374
hi MatchParen     guifg=#D65D0E guibg=#EBDBB2 gui=bold,underline
hi Conceal        guifg=#928374  guibg=#FBF1C7
hi Directory      guifg=#D65D0E gui=bold

" ── Selection / search ────────────────────────────────────────────────────
hi Visual         guibg=#EBDBB2
hi VisualNOS      guibg=#EBDBB2
hi Search         guifg=#FBF1C7     guibg=#B57614 gui=bold
hi IncSearch      guifg=#FBF1C7     guibg=#D65D0E gui=bold
hi CurSearch      guifg=#FBF1C7     guibg=#D65D0E gui=bold
hi QuickFixLine   guibg=#EBDBB2 gui=bold

" ── Popup menu ────────────────────────────────────────────────────────────
hi Pmenu          guifg=#3C3836     guibg=#EBDBB2
hi PmenuSel       guifg=#FBF1C7     guibg=#D65D0E gui=bold
hi PmenuSbar      guibg=#EBDBB2
hi PmenuThumb     guibg=#928374
hi WildMenu       guifg=#FBF1C7     guibg=#D65D0E gui=bold

" ── Messages ──────────────────────────────────────────────────────────────
hi ErrorMsg       guifg=#CC241D    gui=bold
hi WarningMsg     guifg=#B57614
hi ModeMsg        guifg=#D65D0E gui=bold
hi MoreMsg        guifg=#79740E
hi Question       guifg=#D65D0E
hi Title          guifg=#D65D0E gui=bold

" ── Syntax (linked groups) ────────────────────────────────────────────────
hi Comment        guifg=#928374    gui=italic
hi Constant       guifg=#D65D0E
hi String         guifg=#79740E
hi Character      guifg=#79740E
hi Number         guifg=#D65D0E
hi Boolean        guifg=#D65D0E
hi Float          guifg=#D65D0E
hi Identifier     guifg=#3C3836
hi Function       guifg=#D65D0E
hi Statement      guifg=#CC241D
hi Conditional    guifg=#CC241D
hi Repeat         guifg=#CC241D
hi Label          guifg=#B57614
hi Operator       guifg=#076678
hi Keyword        guifg=#CC241D
hi Exception      guifg=#CC241D
hi PreProc        guifg=#B57614
hi Include        guifg=#CC241D
hi Define         guifg=#CC241D
hi Macro          guifg=#D65D0E
hi PreCondit      guifg=#B57614
hi Type           guifg=#B57614
hi StorageClass   guifg=#B57614
hi Structure      guifg=#B57614
hi Typedef        guifg=#B57614
hi Special        guifg=#076678
hi SpecialChar    guifg=#D65D0E
hi Tag            guifg=#D65D0E
hi Delimiter      guifg=#3C3836
hi SpecialComment guifg=#928374    gui=italic
hi Debug          guifg=#D65D0E
hi Underlined     guifg=#D65D0E   gui=underline
hi Ignore         guifg=#928374
hi Error          guifg=#CC241D      gui=bold
hi Todo           guifg=#B57614   guibg=#EBDBB2 gui=bold

" ── Diff ──────────────────────────────────────────────────────────────────
hi DiffAdd        guifg=#79740E    guibg=#FBF1C7
hi DiffChange     guifg=#B57614   guibg=#FBF1C7
hi DiffDelete     guifg=#CC241D      guibg=#FBF1C7
hi DiffText       guifg=#D65D0E   guibg=#FBF1C7    gui=bold
hi diffAdded      guifg=#79740E
hi diffRemoved    guifg=#CC241D
hi diffChanged    guifg=#B57614
hi diffFile       guifg=#D65D0E   gui=bold
hi diffNewFile    guifg=#79740E    gui=bold
hi diffOldFile    guifg=#CC241D      gui=bold
hi diffLine       guifg=#928374

" ── Spelling ──────────────────────────────────────────────────────────────
hi SpellBad       gui=undercurl guisp=#CC241D
hi SpellCap       gui=undercurl guisp=#B57614
hi SpellLocal     gui=undercurl guisp=#076678
hi SpellRare      gui=undercurl guisp=#D03A17

" ── Git plugins / gitgutter / signify ────────────────────────────────────
hi GitGutterAdd          guifg=#79740E    guibg=#FBF1C7
hi GitGutterChange       guifg=#B57614   guibg=#FBF1C7
hi GitGutterDelete       guifg=#CC241D      guibg=#FBF1C7
hi GitGutterChangeDelete guifg=#D65D0E   guibg=#FBF1C7
hi SignifySignAdd        guifg=#79740E    guibg=#FBF1C7
hi SignifySignChange     guifg=#B57614   guibg=#FBF1C7
hi SignifySignDelete     guifg=#CC241D      guibg=#FBF1C7

" ── Markdown ──────────────────────────────────────────────────────────────
hi link markdownH1        Title
hi link markdownH2        Title
hi link markdownH3        Title
hi link markdownH4        Title
hi link markdownCode      String
hi link markdownCodeBlock String
hi link markdownLinkText  Function
hi markdownUrl   guifg=#076678  gui=underline

" ── Vim help ──────────────────────────────────────────────────────────────
hi link helpHyperTextEntry Underlined
hi link helpHyperTextJump  Underlined
hi link helpHeader         Title
hi link helpExample        String
hi link helpOption         Type
hi link helpVim            Identifier

" ── Misc plugins ──────────────────────────────────────────────────────────
hi link NvimTreeFolderName Directory
hi link NvimTreeRootFolder Title
hi link TelescopeBorder    FloatBorder
hi FloatBorder    guifg=#928374    guibg=#FBF1C7
hi NormalFloat    guifg=#3C3836       guibg=#EBDBB2
