# Generated by `aibox` — do NOT edit. Re-run `aibox theme` to refresh.
# Exports keep ANSI-colored tools (bat, delta, fzf, eza, less) aligned with
# the active aibox theme.

export BAT_THEME="gruvbox-light"
export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:-} --color=bg+:#EBDBB2,bg:#FBF1C7,fg:#3C3836,fg+:#3C3836,hl:#D65D0E,hl+:#D65D0E,pointer:#D65D0E,marker:#79740E,spinner:#D65D0E,info:#928374,header:#928374,border:#928374,prompt:#D65D0E,query:#3C3836,disabled:#928374,gutter:#FBF1C7,preview-bg:#FBF1C7,preview-fg:#3C3836,separator:#928374,label:#D65D0E"
export EZA_COLORS="di=38;2;214;93;14;1:ex=38;2;121;116;14:ln=38;2;7;102;120:fi=0:or=38;2;204;36;29:mi=38;2;204;36;29:da=38;2;146;131;116:sn=38;2;214;93;14:sb=38;2;214;93;14:uu=38;2;146;131;116:un=38;2;146;131;116:gu=38;2;146;131;116:gn=38;2;146;131;116:ga=38;2;121;116;14:gm=38;2;181;118;20:gd=38;2;204;36;29:gv=38;2;181;118;20:gt=38;2;214;93;14:xx=38;2;146;131;116:da=38;2;146;131;116"

# `less` headings / search hits — match prompt accent / warnings.
export LESS_TERMCAP_md=$'\e[38;2;214;93;14m'    # bold (section headers, command names)
export LESS_TERMCAP_us=$'\e[38;2;181;118;20m'    # underline (options, args)
export LESS_TERMCAP_so=$'\e[38;2;214;93;14;7m'  # reverse (search / status line)
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export GROFF_NO_SGR=1                  # tell groff to emit ANSI, not SGR-bypass
unset LESS_TERMCAP_mb || true
# Keep an obvious error color available for tools that look for $AIBOX_ERROR_COLOR.
export AIBOX_ERROR_SGR='38;2;204;36;29'
