" aibox.vim — generated by aibox CLI from the active theme palette.
" Do NOT edit; re-run `aibox theme` to regenerate.

hi clear
if exists("syntax_on")
  syntax reset
endif
let g:colors_name = "aibox"
set background=light

" ── UI chrome ──────────────────────────────────────────────────────────────
hi Normal         guifg=#3C3836     guibg=#FBF1C7     ctermfg=NONE ctermbg=NONE
hi NormalNC       guifg=#3C3836     guibg=#FBF1C7
hi Cursor         guifg=#FFFFFF guibg=#AF3A03
hi lCursor        guifg=#FFFFFF guibg=#AF3A03
hi LineNr         guifg=#786B5F  guibg=#FBF1C7
hi CursorLineNr   guifg=#AF3A03 guibg=#E6DDB7 gui=bold
hi CursorLine     guibg=#E6DDB7
hi CursorColumn   guibg=#E6DDB7
hi ColorColumn    guibg=#E6DDB7
hi VertSplit      guifg=#786B5F  guibg=#FBF1C7
hi WinSeparator   guifg=#786B5F  guibg=#FBF1C7
hi StatusLine     guifg=#FFFFFF guibg=#AF3A03 gui=bold
hi StatusLineNC   guifg=#786B5F  guibg=#E6DDB7 gui=NONE
hi TabLine        guifg=#786B5F  guibg=#E6DDB7 gui=NONE
hi TabLineFill    guibg=#FBF1C7
hi TabLineSel     guifg=#FFFFFF guibg=#AF3A03 gui=bold
hi SignColumn     guifg=#786B5F  guibg=#FBF1C7
hi FoldColumn     guifg=#786B5F  guibg=#FBF1C7
hi Folded         guifg=#786B5F  guibg=#E6DDB7
hi NonText        guifg=#786B5F
hi EndOfBuffer    guifg=#FBF1C7     guibg=#FBF1C7
hi SpecialKey     guifg=#786B5F
hi MatchParen     guifg=#AF3A03 guibg=#E6DDB7 gui=bold
hi Conceal        guifg=#786B5F  guibg=#FBF1C7
hi Directory      guifg=#AF3A03 gui=bold

" ── Selection / search ────────────────────────────────────────────────────
hi Visual         guifg=#000000 guibg=#E9C598
hi VisualNOS      guifg=#000000 guibg=#E9C598
hi Search         guifg=#FBF1C7     guibg=#946110 gui=bold
hi IncSearch      guifg=#FBF1C7     guibg=#AF3A03 gui=bold
hi CurSearch      guifg=#FFFFFF guibg=#AF3A03 gui=bold
hi QuickFixLine   guibg=#E6DDB7 gui=bold

" ── Popup menu ────────────────────────────────────────────────────────────
hi Pmenu          guifg=#3C3836     guibg=#E6DDB7
hi PmenuSel       guifg=#FFFFFF guibg=#AF3A03 gui=bold
hi PmenuSbar      guibg=#E6DDB7
hi PmenuThumb     guibg=#786B5F
hi WildMenu       guifg=#FFFFFF guibg=#AF3A03 gui=bold

" ── Messages ──────────────────────────────────────────────────────────────
hi ErrorMsg       guifg=#9D0006    gui=bold
hi WarningMsg     guifg=#946110 gui=bold
hi ModeMsg        guifg=#AF3A03 gui=bold
hi MoreMsg        guifg=#746F0D
hi Question       guifg=#AF3A03
hi Title          guifg=#AF3A03 gui=bold

" ── Syntax (linked groups) ────────────────────────────────────────────────
hi Comment        guifg=#786B5F    gui=italic
hi Constant       guifg=#AF3A03
hi String         guifg=#746F0D     gui=NONE
hi Character      guifg=#746F0D     gui=NONE
hi Number         guifg=#AF3A03    gui=NONE
hi Boolean        guifg=#AF3A03    gui=NONE
hi Float          guifg=#AF3A03    gui=NONE
hi Identifier     guifg=#3C3836
hi Function       guifg=#417956      gui=NONE
hi Statement      guifg=#8F3F71  gui=bold
hi Conditional    guifg=#8F3F71  gui=bold
hi Repeat         guifg=#8F3F71  gui=bold
hi Label          guifg=#946110
hi Operator       guifg=#417956      gui=NONE
hi Keyword        guifg=#8F3F71  gui=bold
hi Exception      guifg=#8F3F71  gui=bold
hi PreProc        guifg=#8F3F71
hi Include        guifg=#8F3F71
hi Define         guifg=#8F3F71
hi Macro          guifg=#AF3A03   gui=italic
hi PreCondit      guifg=#946110
hi Type           guifg=#946110   gui=bold
hi StorageClass   guifg=#946110   gui=bold
hi Structure      guifg=#946110   gui=bold
hi Typedef        guifg=#946110   gui=bold
hi Special        guifg=#417956
hi SpecialChar    guifg=#AF3A03
hi Tag            guifg=#AF3A03
hi Delimiter      guifg=#3C3836
hi SpecialComment guifg=#786B5F    gui=italic
hi Debug          guifg=#AF3A03
hi Underlined     guifg=#AF3A03   gui=underline
hi Ignore         guifg=#786B5F
hi Error          guifg=#9D0006      gui=bold
hi Todo           guifg=#946110   guibg=#E6DDB7 gui=bold

" ── Diff ──────────────────────────────────────────────────────────────────
hi DiffAdd        guifg=#746F0D    guibg=#E5DCA9
hi DiffChange     guifg=#946110   guibg=#EBDAAA
hi DiffDelete     guifg=#9D0006      guibg=#ECCAA8
hi DiffText       guifg=#AF3A03   guibg=#EBDAAA gui=bold
hi diffAdded      guifg=#746F0D
hi diffRemoved    guifg=#9D0006
hi diffChanged    guifg=#946110
hi diffFile       guifg=#AF3A03   gui=bold
hi diffNewFile    guifg=#746F0D    gui=bold
hi diffOldFile    guifg=#9D0006      gui=bold
hi diffLine       guifg=#786B5F

" ── Spelling ──────────────────────────────────────────────────────────────
hi SpellBad       gui=undercurl guisp=#9D0006
hi SpellCap       gui=undercurl guisp=#946110
hi SpellLocal     gui=undercurl guisp=#417956
hi SpellRare      gui=undercurl guisp=#8F3F71

" ── Git plugins / gitgutter / signify ────────────────────────────────────
hi GitGutterAdd          guifg=#746F0D    guibg=#FBF1C7
hi GitGutterChange       guifg=#946110   guibg=#FBF1C7
hi GitGutterDelete       guifg=#9D0006      guibg=#FBF1C7
hi GitGutterChangeDelete guifg=#AF3A03   guibg=#FBF1C7
hi SignifySignAdd        guifg=#746F0D    guibg=#FBF1C7
hi SignifySignChange     guifg=#946110   guibg=#FBF1C7
hi SignifySignDelete     guifg=#9D0006      guibg=#FBF1C7

" ── Markdown ──────────────────────────────────────────────────────────────
hi link markdownH1        Title
hi link markdownH2        Title
hi link markdownH3        Title
hi link markdownH4        Title
hi link markdownCode      String
hi link markdownCodeBlock String
hi link markdownLinkText  Function
hi markdownUrl   guifg=#417956  gui=underline

" ── Vim help ──────────────────────────────────────────────────────────────
hi link helpHyperTextEntry Underlined
hi link helpHyperTextJump  Underlined
hi link helpHeader         Title
hi link helpExample        String
hi link helpOption         Type
hi link helpVim            Identifier

" ── Misc plugins ──────────────────────────────────────────────────────────
hi link NvimTreeFolderName Directory
hi link NvimTreeRootFolder Title
hi link TelescopeBorder    FloatBorder
hi FloatBorder    guifg=#786B5F    guibg=#FBF1C7
hi NormalFloat    guifg=#3C3836       guibg=#E6DDB7
