# Generated by `aibox` — do NOT edit. Re-run `aibox theme` to refresh.
# Exports keep ANSI-colored tools (bat, delta, fzf, eza, less) aligned with
# the active aibox theme.

export BAT_THEME="aibox"
# Bat indexes custom TextMate themes into its cache. Rebuild only when the
# generated aibox theme is not present (normally once after apply/theme switch).
if command -v bat >/dev/null 2>&1 && ! bat --list-themes 2>/dev/null | grep -qx 'aibox'; then
    bat cache --build >/dev/null 2>&1 || true
fi
export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:-} --color=bg+:#E9C598,bg:#FBF1C7,fg:#3C3836,fg+:#000000:bold,hl:#AF3A03,hl+:#AF3A03:bold,pointer:#AF3A03,marker:#746F0D,spinner:#AF3A03,info:#786B5F,header:#786B5F,border:#786B5F,prompt:#AF3A03:bold,query:#3C3836,disabled:#786B5F:dim,gutter:#FBF1C7,preview-bg:#FBF1C7,preview-fg:#3C3836,separator:#786B5F,label:#AF3A03"
export EZA_COLORS="di=38;2;175;58;3;1:ex=38;2;116;111;13:ln=38;2;65;121;86:fi=0:or=38;2;157;0;6;1:mi=38;2;157;0;6;1:da=38;2;120;107;95;2:sn=38;2;175;58;3:sb=38;2;175;58;3:uu=38;2;120;107;95:un=38;2;120;107;95:gu=38;2;120;107;95:gn=38;2;120;107;95:ga=38;2;116;111;13;1:gm=38;2;148;97;16;1:gd=38;2;157;0;6;1:gv=38;2;148;97;16:gt=38;2;175;58;3;3:xx=38;2;120;107;95;2:da=38;2;120;107;95;2"

# `less` headings / search hits — match prompt accent / warnings.
export LESS_TERMCAP_md=$'\e[38;2;175;58;3;1m'    # section headers, command names
export LESS_TERMCAP_us=$'\e[38;2;148;97;16;4m'    # options, args
export LESS_TERMCAP_so=$'\e[38;2;175;58;3;7m'  # search / status line
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export GROFF_NO_SGR=1                  # tell groff to emit ANSI, not SGR-bypass
unset LESS_TERMCAP_mb || true
# Keep an obvious error color available for tools that look for $AIBOX_ERROR_COLOR.
export AIBOX_ERROR_SGR='38;2;157;0;6'
