" aibox.vim — generated by aibox CLI from the active theme palette.
" Do NOT edit; re-run `aibox theme` to regenerate.

hi clear
if exists("syntax_on")
  syntax reset
endif
let g:colors_name = "aibox"
set background=dark

" ── UI chrome ──────────────────────────────────────────────────────────────
hi Normal         guifg=#B3B1AD     guibg=#0A0E14     ctermfg=NONE ctermbg=NONE
hi NormalNC       guifg=#B3B1AD     guibg=#0A0E14
hi Cursor         guifg=#000000 guibg=#39BAE6
hi lCursor        guifg=#000000 guibg=#39BAE6
hi LineNr         guifg=#757C84  guibg=#0A0E14
hi CursorLineNr   guifg=#39BAE6 guibg=#1E2226 gui=bold
hi CursorLine     guibg=#1E2226
hi CursorColumn   guibg=#1E2226
hi ColorColumn    guibg=#1E2226
hi VertSplit      guifg=#757C84  guibg=#0A0E14
hi WinSeparator   guifg=#757C84  guibg=#0A0E14
hi StatusLine     guifg=#000000 guibg=#39BAE6 gui=bold
hi StatusLineNC   guifg=#757C84  guibg=#1E2226 gui=NONE
hi TabLine        guifg=#757C84  guibg=#1E2226 gui=NONE
hi TabLineFill    guibg=#0A0E14
hi TabLineSel     guifg=#000000 guibg=#39BAE6 gui=bold
hi SignColumn     guifg=#757C84  guibg=#0A0E14
hi FoldColumn     guifg=#757C84  guibg=#0A0E14
hi Folded         guifg=#757C84  guibg=#1E2226
hi NonText        guifg=#757C84
hi EndOfBuffer    guifg=#0A0E14     guibg=#0A0E14
hi SpecialKey     guifg=#757C84
hi MatchParen     guifg=#39BAE6 guibg=#1E2226 gui=bold
hi Conceal        guifg=#757C84  guibg=#0A0E14
hi Directory      guifg=#39BAE6 gui=bold

" ── Selection / search ────────────────────────────────────────────────────
hi Visual         guifg=#FFFFFF guibg=#194557
hi VisualNOS      guifg=#FFFFFF guibg=#194557
hi Search         guifg=#0A0E14     guibg=#FFB454 gui=bold
hi IncSearch      guifg=#0A0E14     guibg=#FF8F40 gui=bold
hi CurSearch      guifg=#000000 guibg=#39BAE6 gui=bold
hi QuickFixLine   guibg=#1E2226 gui=bold

" ── Popup menu ────────────────────────────────────────────────────────────
hi Pmenu          guifg=#B3B1AD     guibg=#1E2226
hi PmenuSel       guifg=#000000 guibg=#39BAE6 gui=bold
hi PmenuSbar      guibg=#1E2226
hi PmenuThumb     guibg=#757C84
hi WildMenu       guifg=#000000 guibg=#39BAE6 gui=bold

" ── Messages ──────────────────────────────────────────────────────────────
hi ErrorMsg       guifg=#F07178    gui=bold
hi WarningMsg     guifg=#FFB454 gui=bold
hi ModeMsg        guifg=#39BAE6 gui=bold
hi MoreMsg        guifg=#AAD94C
hi Question       guifg=#39BAE6
hi Title          guifg=#39BAE6 gui=bold

" ── Syntax (linked groups) ────────────────────────────────────────────────
hi Comment        guifg=#757C84    gui=italic
hi Constant       guifg=#FF8F40
hi String         guifg=#AAD94C     gui=NONE
hi Character      guifg=#AAD94C     gui=NONE
hi Number         guifg=#FF8F40    gui=NONE
hi Boolean        guifg=#FF8F40    gui=NONE
hi Float          guifg=#FF8F40    gui=NONE
hi Identifier     guifg=#B3B1AD
hi Function       guifg=#95E6CB      gui=NONE
hi Statement      guifg=#D2A6FF  gui=bold
hi Conditional    guifg=#D2A6FF  gui=bold
hi Repeat         guifg=#D2A6FF  gui=bold
hi Label          guifg=#FFB454
hi Operator       guifg=#95E6CB      gui=NONE
hi Keyword        guifg=#D2A6FF  gui=bold
hi Exception      guifg=#D2A6FF  gui=bold
hi PreProc        guifg=#D2A6FF
hi Include        guifg=#D2A6FF
hi Define         guifg=#D2A6FF
hi Macro          guifg=#39BAE6   gui=italic
hi PreCondit      guifg=#FFB454
hi Type           guifg=#FFB454   gui=bold
hi StorageClass   guifg=#FFB454   gui=bold
hi Structure      guifg=#FFB454   gui=bold
hi Typedef        guifg=#FFB454   gui=bold
hi Special        guifg=#95E6CB
hi SpecialChar    guifg=#FF8F40
hi Tag            guifg=#39BAE6
hi Delimiter      guifg=#B3B1AD
hi SpecialComment guifg=#757C84    gui=italic
hi Debug          guifg=#FF8F40
hi Underlined     guifg=#39BAE6   gui=underline
hi Ignore         guifg=#757C84
hi Error          guifg=#F07178      gui=bold
hi Todo           guifg=#FFB454   guibg=#1E2226 gui=bold

" ── Diff ──────────────────────────────────────────────────────────────────
hi DiffAdd        guifg=#AAD94C    guibg=#2D3B20
hi DiffChange     guifg=#FFB454   guibg=#403322
hi DiffDelete     guifg=#F07178      guibg=#3D242A
hi DiffText       guifg=#39BAE6   guibg=#403322 gui=bold
hi diffAdded      guifg=#AAD94C
hi diffRemoved    guifg=#F07178
hi diffChanged    guifg=#FFB454
hi diffFile       guifg=#39BAE6   gui=bold
hi diffNewFile    guifg=#AAD94C    gui=bold
hi diffOldFile    guifg=#F07178      gui=bold
hi diffLine       guifg=#757C84

" ── Spelling ──────────────────────────────────────────────────────────────
hi SpellBad       gui=undercurl guisp=#F07178
hi SpellCap       gui=undercurl guisp=#FFB454
hi SpellLocal     gui=undercurl guisp=#95E6CB
hi SpellRare      gui=undercurl guisp=#D2A6FF

" ── Git plugins / gitgutter / signify ────────────────────────────────────
hi GitGutterAdd          guifg=#AAD94C    guibg=#0A0E14
hi GitGutterChange       guifg=#FFB454   guibg=#0A0E14
hi GitGutterDelete       guifg=#F07178      guibg=#0A0E14
hi GitGutterChangeDelete guifg=#FF8F40   guibg=#0A0E14
hi SignifySignAdd        guifg=#AAD94C    guibg=#0A0E14
hi SignifySignChange     guifg=#FFB454   guibg=#0A0E14
hi SignifySignDelete     guifg=#F07178      guibg=#0A0E14

" ── Markdown ──────────────────────────────────────────────────────────────
hi link markdownH1        Title
hi link markdownH2        Title
hi link markdownH3        Title
hi link markdownH4        Title
hi link markdownCode      String
hi link markdownCodeBlock String
hi link markdownLinkText  Function
hi markdownUrl   guifg=#95E6CB  gui=underline

" ── Vim help ──────────────────────────────────────────────────────────────
hi link helpHyperTextEntry Underlined
hi link helpHyperTextJump  Underlined
hi link helpHeader         Title
hi link helpExample        String
hi link helpOption         Type
hi link helpVim            Identifier

" ── Misc plugins ──────────────────────────────────────────────────────────
hi link NvimTreeFolderName Directory
hi link NvimTreeRootFolder Title
hi link TelescopeBorder    FloatBorder
hi FloatBorder    guifg=#757C84    guibg=#0A0E14
hi NormalFloat    guifg=#B3B1AD       guibg=#1E2226
