#!/usr/bin/env bash
# tmux-powerkit theme — generated by aibox CLI from the active theme palette.
# Loaded via @powerkit_theme "custom" + @powerkit_custom_theme_path.
# Do NOT edit; re-run `aibox theme` to regenerate.

declare -gA THEME_COLORS=(
    # Core
    [background]="#FBF1C7"

    # Status bar
    [statusbar-bg]="#EBDBB2"
    [statusbar-fg]="#3C3836"

    # Session (status-left)
    [session-bg]="#D65D0E"
    [session-fg]="#FBF1C7"
    [session-prefix-bg]="#CC241D"
    [session-copy-bg]="#076678"
    [session-search-bg]="#B57614"
    [session-command-bg]="#D03A17"

    # Windows
    [window-active-base]="#D65D0E"
    [window-active-style]="bold"
    [window-inactive-base]="#928374"
    [window-inactive-style]="none"
    [window-activity-style]="italics"
    [window-bell-style]="bold"
    [window-zoomed-bg]="#076678"

    # Panes
    [pane-border-active]="#D65D0E"
    [pane-border-inactive]="#928374"

    # Health / state segments (chevron color rotation source)
    [ok-base]="#A97550"
    [good-base]="#79740E"
    [info-base]="#076678"
    [warning-base]="#B57614"
    [error-base]="#CC241D"
    [disabled-base]="#928374"

    # Messages
    [message-bg]="#EBDBB2"
    [message-fg]="#3C3836"

    # Popup & menu
    [popup-bg]="#EBDBB2"
    [popup-fg]="#3C3836"
    [popup-border]="#D65D0E"
    [menu-bg]="#EBDBB2"
    [menu-fg]="#3C3836"
    [menu-selected-bg]="#D65D0E"
    [menu-selected-fg]="#FBF1C7"
    [menu-border]="#D65D0E"
)

# Extra slots some plugins read directly — also derived from the palette so
# every chevron lands on a known-good bg.
declare -gA THEME_EXTRA=(
    [orange]="#D65D0E"
    [magenta]="#D03A17"
    [surface]="#EBDBB2"
)
